package com.sola.gifttalk.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH".
*/
public class SearchDao extends AbstractDao<Search, Long> {

    public static final String TABLENAME = "SEARCH";

    /**
     * Properties of entity Search.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Words = new Property(1, String.class, "words", false, "WORDS");
        public final static Property Things = new Property(2, String.class, "things", false, "THINGS");
    }


    public SearchDao(DaoConfig config) {
        super(config);
    }
    
    public SearchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"WORDS\" TEXT," + // 1: words
                "\"THINGS\" TEXT);"); // 2: things
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Search entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String words = entity.getWords();
        if (words != null) {
            stmt.bindString(2, words);
        }
 
        String things = entity.getThings();
        if (things != null) {
            stmt.bindString(3, things);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Search entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String words = entity.getWords();
        if (words != null) {
            stmt.bindString(2, words);
        }
 
        String things = entity.getThings();
        if (things != null) {
            stmt.bindString(3, things);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Search readEntity(Cursor cursor, int offset) {
        Search entity = new Search( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // words
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // things
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Search entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWords(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThings(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Search entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Search entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Search entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
